/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/AppTopbar.vue')['default']
    CampaignCard: typeof import('./components/CampaignCard.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    GlobalSnackbar: typeof import('./components/GlobalSnackbar.vue')['default']
    MessageCard: typeof import('./components/MessageCard.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RecipientPicker: typeof import('./components/compose/RecipientPicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./components/StatCard.vue')['default']
    TiptapEditor: typeof import('./components/compose/TiptapEditor.vue')['default']
  }
}
