/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/AppTopbar.vue')['default']
    CampaignCard: typeof import('./components/CampaignCard.vue')['default']
    CompanyEmailSettings: typeof import('./components/CompanyEmailSettings.vue')['default']
    CompanyOdooSettings: typeof import('./components/CompanyOdooSettings.vue')['default']
    CompanySmsSettings: typeof import('./components/CompanySmsSettings.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    DomainContactsDialog: typeof import('./components/DomainContactsDialog.vue')['default']
    DomainSelect: typeof import('./components/DomainSelect.vue')['default']
    GlobalSnackbar: typeof import('./components/GlobalSnackbar.vue')['default']
    MessageCard: typeof import('./components/MessageCard.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RecipientPicker: typeof import('./components/compose/RecipientPicker.vue')['default']
    RecipientPreviewDialog: typeof import('./components/RecipientPreviewDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleGroupEditor: typeof import('./components/RuleGroupEditor.vue')['default']
    SearchField: typeof import('./components/SearchField.vue')['default']
    StatCard: typeof import('./components/StatCard.vue')['default']
    TiptapEditor: typeof import('./components/compose/TiptapEditor.vue')['default']
  }
}
