/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/assignments': RouteRecordInfo<'/assignments', '/assignments', Record<never, never>, Record<never, never>>,
    '/campaign-detail-[id]': RouteRecordInfo<'/campaign-detail-[id]', '/campaign-detail-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/campaigns': RouteRecordInfo<'/campaigns', '/campaigns', Record<never, never>, Record<never, never>>,
    '/companies': RouteRecordInfo<'/companies', '/companies', Record<never, never>, Record<never, never>>,
    '/compose': RouteRecordInfo<'/compose', '/compose', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/mailing-lists': RouteRecordInfo<'/mailing-lists', '/mailing-lists', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }
}
